spring:
  data:
    mongodb:
      host: my-mongodb
      database: userCollection
      port: 27017
      username: admin
      password: qwerty
      uri: mongodb://admin:qwerty@my-mongodb:27017/

server:
  port: 8080